id: I9CDDC1BA
legacy_id: P007847
ocr_import_info:
  bdrc_scan_id: W1KG21275
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T20:21:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:53:33.032121+00:00'
last_modified: 2022-08-27 14:54:23.962149
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG21275
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG21275
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐབས་དང་པོའི་དོགས་སྤྱོད་བློ་གསལ་རིགས་སྨྲའི་རྒྱན།
  author: སྔགས་ཆེན་བློ་བཟང་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9530652076477122
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG21319:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG21319
      total_pages: 422
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG21319.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9530652076477122
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
