id: I9CDDC1BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:24:06+00:00'
last_modified: '2022-06-09T06:32:46.871619+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21275
  title: སྐབས་དང་པོའི་དོགས་སྤྱོད་བློ་གསལ་རིགས་སྨྲའི་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A949:
      image_group_id: I1KG21319
      title: Volume 1 of skabs dang po'i dogs spyod blo gsal rigs smra'i rgyan/
      total_pages: 422
      order: 1
      base_file: A949.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
