id: P007847
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21275
  title: སྐབས་དང་པོའི་དོགས་སྤྱོད་བློ་གསལ་རིགས་སྨྲའི་རྒྱན།
  author: ''
  volumes:
    bc6baa61cb4e4471a9883078bd066989:
      image_group_id: I1KG21319
      title: ''
      volume_number: 1
      total_pages: 422
ebook_metadata:
  title: སྐབས་དང་པོའི་དོགས་སྤྱོད་བློ་གསལ་རིགས་སྨྲའི་རྒྱན།
  author: ''
  sku: P007847
  cover: cover.jpg
  layers:
  - pagination
