id: P007847
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21275
  title: སྐབས་དང་པོའི་དོགས་སྤྱོད་བློ་གསལ་རིགས་སྨྲའི་རྒྱན།
  author: ''
  volumes:
    ba167f7693c541fbb6a9633e4d7d5377:
      image_group_id: I1KG21319
      title: Volume 1 of skabs dang po'i dogs spyod blo gsal rigs smra'i rgyan/
      volume_number: 1
      total_pages: 422
      base_file: v001.txt
ebook_metadata:
  title: སྐབས་དང་པོའི་དོགས་སྤྱོད་བློ་གསལ་རིགས་སྨྲའི་རྒྱན།
  author: ''
  sku: P007847
  cover: cover.jpg
  layers:
  - pagination
